/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StructsReplyButton model module.
 * @module model/StructsReplyButton
 * @version 1.0.0
 */
class StructsReplyButton {
    /**
     * Constructs a new <code>StructsReplyButton</code>.
     * @alias module:model/StructsReplyButton
     */
    constructor() { 
        
        StructsReplyButton.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StructsReplyButton</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StructsReplyButton} obj Optional instance to populate.
     * @return {module:model/StructsReplyButton} The populated <code>StructsReplyButton</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StructsReplyButton();

            if (data.hasOwnProperty('button_id')) {
                obj['button_id'] = ApiClient.convertToType(data['button_id'], 'String');
            }
            if (data.hasOwnProperty('button_text')) {
                obj['button_text'] = ApiClient.convertToType(data['button_text'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StructsReplyButton</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StructsReplyButton</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['button_id'] && !(typeof data['button_id'] === 'string' || data['button_id'] instanceof String)) {
            throw new Error("Expected the field `button_id` to be a primitive type in the JSON string but got " + data['button_id']);
        }
        // ensure the json data is a string
        if (data['button_text'] && !(typeof data['button_text'] === 'string' || data['button_text'] instanceof String)) {
            throw new Error("Expected the field `button_text` to be a primitive type in the JSON string but got " + data['button_text']);
        }

        return true;
    }


}



/**
 * @member {String} button_id
 */
StructsReplyButton.prototype['button_id'] = undefined;

/**
 * @member {String} button_text
 */
StructsReplyButton.prototype['button_text'] = undefined;






export default StructsReplyButton;

