/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContactMessagePayloadVcard from './ContactMessagePayloadVcard';

/**
 * The ContactMessagePayload model module.
 * @module WhatsAPI/models/ContactMessagePayload
 * @version 1.0.0
 */
class ContactMessagePayload {
    /**
     * Constructs a new <code>ContactMessagePayload</code>.
     * @alias module:WhatsAPI/models/ContactMessagePayload
     * @param to {String} 
     * @param vcard {module:WhatsAPI/models/ContactMessagePayloadVcard} 
     */
    constructor(to, vcard) { 
        
        ContactMessagePayload.initialize(this, to, vcard);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, to, vcard) { 
        obj['to'] = to;
        obj['vcard'] = vcard;
    }

    /**
     * Constructs a <code>ContactMessagePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:WhatsAPI/models/ContactMessagePayload} obj Optional instance to populate.
     * @return {module:WhatsAPI/models/ContactMessagePayload} The populated <code>ContactMessagePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactMessagePayload();

            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('vcard')) {
                obj['vcard'] = ContactMessagePayloadVcard.constructFromObject(data['vcard']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactMessagePayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactMessagePayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContactMessagePayload.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['to'] && !(typeof data['to'] === 'string' || data['to'] instanceof String)) {
            throw new Error("Expected the field `to` to be a primitive type in the JSON string but got " + data['to']);
        }
        // validate the optional field `vcard`
        if (data['vcard']) { // data not null
          ContactMessagePayloadVcard.validateJSON(data['vcard']);
        }

        return true;
    }


}

ContactMessagePayload.RequiredProperties = ["to", "vcard"];

/**
 * @member {String} to
 */
ContactMessagePayload.prototype['to'] = undefined;

/**
 * @member {module:WhatsAPI/models/ContactMessagePayloadVcard} vcard
 */
ContactMessagePayload.prototype['vcard'] = undefined;






export default ContactMessagePayload;

