/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateInstancePayload model module.
 * @module WhatsAPI/models/CreateInstancePayload
 * @version 1.0.0
 */
class CreateInstancePayload {
    /**
     * Constructs a new <code>CreateInstancePayload</code>.
     * @alias module:WhatsAPI/models/CreateInstancePayload
     */
    constructor() { 
        
        CreateInstancePayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateInstancePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:WhatsAPI/models/CreateInstancePayload} obj Optional instance to populate.
     * @return {module:WhatsAPI/models/CreateInstancePayload} The populated <code>CreateInstancePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateInstancePayload();

            if (data.hasOwnProperty('instance_key')) {
                obj['instance_key'] = ApiClient.convertToType(data['instance_key'], 'String');
            }
            if (data.hasOwnProperty('webhook_url')) {
                obj['webhook_url'] = ApiClient.convertToType(data['webhook_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateInstancePayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateInstancePayload</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['instance_key'] && !(typeof data['instance_key'] === 'string' || data['instance_key'] instanceof String)) {
            throw new Error("Expected the field `instance_key` to be a primitive type in the JSON string but got " + data['instance_key']);
        }
        // ensure the json data is a string
        if (data['webhook_url'] && !(typeof data['webhook_url'] === 'string' || data['webhook_url'] instanceof String)) {
            throw new Error("Expected the field `webhook_url` to be a primitive type in the JSON string but got " + data['webhook_url']);
        }

        return true;
    }


}



/**
 * @member {String} instance_key
 */
CreateInstancePayload.prototype['instance_key'] = undefined;

/**
 * @member {String} webhook_url
 */
CreateInstancePayload.prototype['webhook_url'] = undefined;






export default CreateInstancePayload;

