/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GroupUpdateDescriptionPayload model module.
 * @module WhatsAPI/models/GroupUpdateDescriptionPayload
 * @version 1.0.0
 */
class GroupUpdateDescriptionPayload {
    /**
     * Constructs a new <code>GroupUpdateDescriptionPayload</code>.
     * @alias module:WhatsAPI/models/GroupUpdateDescriptionPayload
     */
    constructor() { 
        
        GroupUpdateDescriptionPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupUpdateDescriptionPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:WhatsAPI/models/GroupUpdateDescriptionPayload} obj Optional instance to populate.
     * @return {module:WhatsAPI/models/GroupUpdateDescriptionPayload} The populated <code>GroupUpdateDescriptionPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupUpdateDescriptionPayload();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GroupUpdateDescriptionPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GroupUpdateDescriptionPayload</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {String} description
 */
GroupUpdateDescriptionPayload.prototype['description'] = undefined;






export default GroupUpdateDescriptionPayload;

