/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StructsGroupUpdateParticipantsPayload model module.
 * @module WhatsAPI/models/StructsGroupUpdateParticipantsPayload
 * @version 1.0.0
 */
class StructsGroupUpdateParticipantsPayload {
    /**
     * Constructs a new <code>StructsGroupUpdateParticipantsPayload</code>.
     * @alias module:WhatsAPI/models/StructsGroupUpdateParticipantsPayload
     */
    constructor() { 
        
        StructsGroupUpdateParticipantsPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StructsGroupUpdateParticipantsPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:WhatsAPI/models/StructsGroupUpdateParticipantsPayload} obj Optional instance to populate.
     * @return {module:WhatsAPI/models/StructsGroupUpdateParticipantsPayload} The populated <code>StructsGroupUpdateParticipantsPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StructsGroupUpdateParticipantsPayload();

            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StructsGroupUpdateParticipantsPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StructsGroupUpdateParticipantsPayload</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['participants'])) {
            throw new Error("Expected the field `participants` to be an array in the JSON data but got " + data['participants']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} participants
 */
StructsGroupUpdateParticipantsPayload.prototype['participants'] = undefined;






export default StructsGroupUpdateParticipantsPayload;

