/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WhatsApiGo);
  }
}(this, function(expect, WhatsApiGo) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WhatsApiGo.MessageSendingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MessageSendingApi', function() {
    describe('instancesInstanceKeyBusinessCatalogGet', function() {
      it('should call instancesInstanceKeyBusinessCatalogGet successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeyBusinessCatalogGet
        //instance.instancesInstanceKeyBusinessCatalogGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendAudioPost', function() {
      it('should call instancesInstanceKeySendAudioPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendAudioPost
        //instance.instancesInstanceKeySendAudioPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendButtonMediaPost', function() {
      it('should call instancesInstanceKeySendButtonMediaPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendButtonMediaPost
        //instance.instancesInstanceKeySendButtonMediaPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendButtonsPost', function() {
      it('should call instancesInstanceKeySendButtonsPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendButtonsPost
        //instance.instancesInstanceKeySendButtonsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendContactPost', function() {
      it('should call instancesInstanceKeySendContactPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendContactPost
        //instance.instancesInstanceKeySendContactPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendDocumentPost', function() {
      it('should call instancesInstanceKeySendDocumentPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendDocumentPost
        //instance.instancesInstanceKeySendDocumentPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendImagePost', function() {
      it('should call instancesInstanceKeySendImagePost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendImagePost
        //instance.instancesInstanceKeySendImagePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendListPost', function() {
      it('should call instancesInstanceKeySendListPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendListPost
        //instance.instancesInstanceKeySendListPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendLocationPost', function() {
      it('should call instancesInstanceKeySendLocationPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendLocationPost
        //instance.instancesInstanceKeySendLocationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendMediaPost', function() {
      it('should call instancesInstanceKeySendMediaPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendMediaPost
        //instance.instancesInstanceKeySendMediaPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendPollPost', function() {
      it('should call instancesInstanceKeySendPollPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendPollPost
        //instance.instancesInstanceKeySendPollPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendTemplateMediaPost', function() {
      it('should call instancesInstanceKeySendTemplateMediaPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendTemplateMediaPost
        //instance.instancesInstanceKeySendTemplateMediaPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendTemplatePost', function() {
      it('should call instancesInstanceKeySendTemplatePost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendTemplatePost
        //instance.instancesInstanceKeySendTemplatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendTextPost', function() {
      it('should call instancesInstanceKeySendTextPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendTextPost
        //instance.instancesInstanceKeySendTextPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendUploadPost', function() {
      it('should call instancesInstanceKeySendUploadPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendUploadPost
        //instance.instancesInstanceKeySendUploadPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('instancesInstanceKeySendVideoPost', function() {
      it('should call instancesInstanceKeySendVideoPost successfully', function(done) {
        //uncomment below and update the code to test instancesInstanceKeySendVideoPost
        //instance.instancesInstanceKeySendVideoPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
